<?php 
/**
 * TestNamespace_TestModule extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       TestNamespace
 * @package        TestNamespace_TestModule
 * @copyright      Copyright (c) 2015
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * ImageURL list template
 *
 * @category    TestNamespace
 * @package     TestNamespace_TestModule
 * @author      Ultimate Module Creator
 */
?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php $_imagesurl = $this->getImagesurl(); ?>
<div class="page-title imageurl-title">
    <?php if (Mage::helper('testnamespace_testmodule/imageurl')->isRssEnabled()) : ?>
        <a href="<?php echo Mage::helper('testnamespace_testmodule/imageurl')->getRssUrl();?>" class="link-rss"><?php echo Mage::helper('testnamespace_testmodule')->__('Subscribe to RSS Feed')?></a>
    <?php endif;?>
    <h1><?php echo Mage::helper('testnamespace_testmodule')->__('ImagesURL') ?></h1>
</div>
<?php if ($_imagesurl->getSize() > 0) :?>
    <?php echo $this->getPagerHtml(); ?>
    <div class="imageurl-list-container">
    <?php foreach ($_imagesurl as $_imageurl) : ?>
        <div class="imageurl-list-item">
            <a href="<?php echo $_imageurl->getImageurlUrl()?>">
                <?php echo $_imageurl->getAbclink();?>
            </a><br />
        </div>
    <?php endforeach;?>
    </div>
    <?php echo $this->getPagerHtml(); ?>
<?php else : ?>
    <?php echo Mage::helper('testnamespace_testmodule')->__('There are no imagesurl at this moment');?>
<?php endif;?>
