<?php
/**
 * TestNamespace_TestModule extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       TestNamespace
 * @package        TestNamespace_TestModule
 * @copyright      Copyright (c) 2015
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * ImageURL view template
 *
 * @category    TestNamespace
 * @package     TestNamespace_TestModule
 * @author      Ultimate Module Creator
 */
?>
<?php $_imageurl = $this->getCurrentImageurl();?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="page-title imageurl-title">
    <h1><?php echo $_imageurl->getAbclink(); ?></h1>
</div>
<div class="imageurl-view">
    <div class="imageurl-abclink">
        <?php echo Mage::helper('testnamespace_testmodule')->__('ABC Link');?>:<?php echo $_imageurl->getAbclink();?>

    </div>

</div>
