<?php
/**
 * TestNamespace_TestModule extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       TestNamespace
 * @package        TestNamespace_TestModule
 * @copyright      Copyright (c) 2015
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * ImageURL link widget template
 *
 * @category    TestNamespace
 * @package     TestNamespace_TestModule
 * @author      Ultimate Module Creator
 */
?>
<?php $_imageurl = $this->getCurrentImageurl();?>
<?php if ($_imageurl) :?>
    <div class="imageurl-widget-link">
        <a href="<?php echo $_imageurl->getImageurlUrl()?>"><?php echo $_imageurl->getAbclink()?></a>
    </div>
<?php endif;?>
